---
title: "data_preprocessing"
author: "Adam Drożyński"
date: "4/2/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
library(pacman)
p_load(tictoc,tidyverse,dplyr,broom,ggplot2,clubSandwich,
       data.table,matrixStats,magrittr,MASS,R.utils,
       stargazer,DT,furrr, lfe,estimatr,boot,plm,lmtest,multiwayvcov,
       sandwich,glmnet,ISLR, parallel, haven, MatchIt, optmatch, ipw, AER, rdd)
PATH_BHPS = '..\\UKDA-6614-stata\\stata\\stata13_se\\bhps\\'
# PATH_BHPS = '../UKDA-6614-stata/stata/stata13_se/bhps/'
PATH_UKHLS = '..\\UKDA-6614-stata\\stata\\stata13_se\\ukhls\\'
# PATH_UKHLS = '../UKDA-6614-stata/stata/stata13_se/ukhls/'
```


```{r}
get_full_label_bhps <- function(label, letter){
  return(paste0('b', letter, '_', label))
}

read_bhps_by_letter <- function(x){
  data <- read_stata(paste0(PATH_BHPS, 'b', x, '_youth.dta'))
  data <- data %>% dplyr::select(any_of(c('pidp', 
                         get_full_label_bhps('ypdoby', x),
                         get_full_label_bhps('ypsex', x),
                         get_full_label_bhps('ypnpal', x),
                         get_full_label_bhps('ypfpark', x),
                         get_full_label_bhps('ypmkfrn', x),
                         get_full_label_bhps('yppalo', x),
                         get_full_label_bhps('yppals', x),
                         get_full_label_bhps('ypsdqk', x)))) %>% 
          rename_with(~ 'birthy', all_of(get_full_label_bhps('ypdoby', x))) %>% 
          rename_with(~ 'sex', all_of(get_full_label_bhps('ypsex', x))) %>%
          rename_with(~ case_when(. == get_full_label_bhps('ypnpal', x) ~ 'ypnpal', 
                                  . == get_full_label_bhps('ypfpark', x) ~ 'ypfpark', 
                                  . == get_full_label_bhps('ypmkfrn', x) ~ 'ypmkfrn', 
                                  . == get_full_label_bhps('yppalo', x) ~ 'yppalo', 
                                  . == get_full_label_bhps('yppals', x) ~ 'yppals',
                                  . == get_full_label_bhps('ypsdqk', x) ~ 'ypsdqk',
                                  TRUE ~ .))
  data$birthy = ifelse(data$birthy > 1000, data$birthy, data$birthy + 1900)
  data$year = 1991 + (utf8ToInt(x) - utf8ToInt('a'))
  data$age = data$year - data$birthy
  return(data)
}


data_youth <- lapply(letters[4:18], read_bhps_by_letter)

data_youth_merged <- rbindlist(data_youth, fill = T)

data_youth_merged$ypnpal <- 
  ifelse(data_youth_merged$ypnpal >= 0, data_youth_merged$ypnpal, NaN)
data_youth_merged$ypfpark <- 
  ifelse(data_youth_merged$ypfpark >= 0, data_youth_merged$ypfpark, NaN)
data_youth_merged$ypmkfrn <- 
  ifelse(data_youth_merged$ypmkfrn >= 0, data_youth_merged$ypmkfrn, NaN)
data_youth_merged$yppalo <- 
  ifelse(data_youth_merged$yppalo >= 0, data_youth_merged$yppalo, NaN)
data_youth_merged$yppals <- 
  ifelse(data_youth_merged$yppals >= 0, data_youth_merged$yppals, NaN)
data_youth_merged$ypsdqk <- 
  ifelse(data_youth_merged$ypsdqk >= 0, data_youth_merged$ypsdqk, NaN)
```

```{r}
get_full_label_ukhls <- function(label, letter){
  return(paste0(letter, '_', label))
}

read_ukhls_by_letter <- function(x){
  data <- read_stata(paste0(PATH_UKHLS, x, '_indresp.dta'))
  data <- data %>% dplyr::select(any_of(c('pidp', 
                         get_full_label_ukhls('birthy', x),
                         get_full_label_ukhls('sex', x),
                         get_full_label_ukhls('adcts', x),
                         get_full_label_ukhls('memploy', x),
                         get_full_label_ukhls('family', x),
                         get_full_label_ukhls('education', x),
                         get_full_label_ukhls('housing', x),
                         get_full_label_ukhls('area', x),
                         get_full_label_ukhls('fimnlabnet_dv', x)))) %>% 
          rename_with(~ 'birthy', all_of(get_full_label_ukhls('birthy', x))) %>% 
          rename_with(~ 'sex', all_of(get_full_label_ukhls('sex', x))) %>%
          rename_with(~ 'moved', all_of(get_full_label_ukhls('adcts', x))) %>%
          rename_with(~ 'memploy', all_of(get_full_label_ukhls('memploy', x))) %>%
          rename_with(~ 'family', all_of(get_full_label_ukhls('family', x))) %>%
          rename_with(~ 'education', all_of(get_full_label_ukhls('education', x))) %>%
          rename_with(~ 'housing', all_of(get_full_label_ukhls('housing', x))) %>%
          rename_with(~ 'area', all_of(get_full_label_ukhls('area', x))) %>%
          rename_with(~ 'income', all_of(get_full_label_ukhls('fimnlabnet_dv', x)))
  data$birthy = ifelse(data$birthy > 1000, data$birthy, data$birthy + 1900)
  data$year = 2009 + (utf8ToInt(x) - utf8ToInt('a'))
  data$age = data$year - data$birthy
  return(data)
}

data_adults <- lapply(letters[3:11], read_ukhls_by_letter)
data_adults_merged <- rbindlist(data_adults)
```


Moving - data preparation
```{r}
data_adults_merged$moved_bin = 1*(data_adults_merged$moved == 1)
data_adults_merged$moved_for_job = 1*(data_adults_merged$memploy > 0)
data_adults_merged$moved_for_family = 1*(data_adults_merged$family > 0)
data_adults_merged$moved_for_education = 1*(data_adults_merged$education > 0)
data_adults_merged$moved_for_housing = 1*(data_adults_merged$housing > 0)
data_adults_merged$moved_for_area = 1*(data_adults_merged$area > 0)

data_adults_merged <- data_adults_merged %>%
    group_by(pidp) %>%
    arrange(year, .by_group = T) %>%
    mutate(moved_times = cumsum(moved_bin))

data_adults_merged <- data_adults_merged %>%
    group_by(pidp) %>%
    arrange(year, .by_group = T) %>%
    mutate(moved_for_job_times = cumsum(moved_for_job))

data_adults_merged <- data_adults_merged %>%
    group_by(pidp) %>%
    arrange(year, .by_group = T) %>%
    mutate(moved_for_family_times = cumsum(moved_for_family))

data_adults_merged <- data_adults_merged %>%
    group_by(pidp) %>%
    arrange(year, .by_group = T) %>%
    mutate(moved_for_education_times = cumsum(moved_for_education))

data_adults_merged <- data_adults_merged %>%
    group_by(pidp) %>%
    arrange(year, .by_group = T) %>%
    mutate(moved_for_housing_times = cumsum(moved_for_housing))

data_adults_merged <- data_adults_merged %>%
    group_by(pidp) %>%
    arrange(year, .by_group = T) %>%
    mutate(moved_for_area_times = cumsum(moved_for_area))


data_adults_merged <- data_adults_merged %>% 
  group_by(pidp) %>% 
  arrange(year, .by_group = T) %>%
  mutate(moved_total = sum(moved_bin))

data_adults_merged <- data_adults_merged %>% 
  group_by(pidp) %>% 
  arrange(year, .by_group = T) %>%
  mutate(moved_for_job_total = sum(moved_for_job))

data_adults_merged <- data_adults_merged %>% 
  group_by(pidp) %>% 
  arrange(year, .by_group = T) %>%
  mutate(moved_for_family_total = sum(moved_for_family))

data_adults_merged <- data_adults_merged %>% 
  group_by(pidp) %>% 
  arrange(year, .by_group = T) %>%
  mutate(moved_for_education_total = sum(moved_for_education))

data_adults_merged <- data_adults_merged %>% 
  group_by(pidp) %>% 
  arrange(year, .by_group = T) %>%
  mutate(moved_for_housing_total = sum(moved_for_housing))

data_adults_merged <- data_adults_merged %>% 
  group_by(pidp) %>% 
  arrange(year, .by_group = T) %>%
  mutate(moved_for_area_total = sum(moved_for_area))
```

Moving - regressions
```{r}
lm1 <- felm(income ~ moved_times | year + pidp + age | 0 | pidp, 
       data = data_adults_merged)
lm2 <- felm(income ~ moved_for_job_times | year + pidp + age | 0 | pidp, 
       data = data_adults_merged)
lm3 <- felm(income ~ moved_for_family_times | year + pidp + age | 0 | pidp, 
       data = data_adults_merged)
lm4 <- felm(income ~ moved_for_education_times | year + pidp + age | 0 | pidp, 
       data = data_adults_merged)
lm5 <- felm(income ~ moved_for_housing_times | year + pidp + age | 0 | pidp, 
       data = data_adults_merged)
lm6 <- felm(income ~ moved_for_area_times | year + pidp + age | 0 | pidp, 
       data = data_adults_merged)


lm7 <- 
  felm(income ~ moved_times + moved_for_job_times + 
                moved_for_family_times + moved_for_education_times +
                moved_for_housing_times + moved_for_area_times 
                  | year + pidp + age | 0 | pidp, 
       data = data_adults_merged)

stargazer(lm1, lm2, lm3, lm4, lm5, omit.stat = c("adj.rsq","ser", "f"),
          omit.table.layout = c("n"), type = 'text')
stargazer(lm6, lm7, omit.stat = c("adj.rsq","ser", "f"),
          omit.table.layout = c("n"), type = 'text')
```

Social skills - data preparation
```{r}
data_adults_moves <- data_adults_merged %>% 
  dplyr::select(pidp, birthy, sex, moved_total, moved_for_job_total, 
                moved_for_education_total)
data_adults_moves <- unique(data_adults_moves)


data_youth_merged_11 <- data_youth_merged %>% dplyr::filter(age == 11)
full_data_merge_11 <- data_adults_moves %>% 
  inner_join(data_youth_merged_11, by = c('pidp', 'birthy', 'sex'))

data_youth_merged_13 <- data_youth_merged %>% dplyr::filter(age == 13)
full_data_merge_13 <- data_adults_moves %>% 
  inner_join(data_youth_merged_13, by = c('pidp', 'birthy', 'sex'))


data_youth_merged_15 <- data_youth_merged %>% dplyr::filter(age == 15)
full_data_merge_15 <- data_adults_moves %>% 
  inner_join(data_youth_merged_15, by = c('pidp', 'birthy', 'sex'))
```

Social skills - regressions
```{r}
stargazer(lm(moved_total ~ ypnpal, data = full_data_merge_11),
          lm(moved_total ~ ypfpark, data = full_data_merge_11),
          lm(moved_total ~ ypmkfrn, data = full_data_merge_11),
          lm(moved_total ~ yppalo, data = full_data_merge_11),
          lm(moved_total ~ yppals, data = full_data_merge_11),
          omit.stat = c("adj.rsq","ser", "f"),
          omit.table.layout = c("n"),
          type = 'text')

stargazer(lm(moved_for_job_total ~ ypnpal, data = full_data_merge_11),
          lm(moved_for_job_total ~ ypfpark, data = full_data_merge_11),
          lm(moved_for_job_total ~ ypmkfrn, data = full_data_merge_11),
          lm(moved_for_job_total ~ yppalo, data = full_data_merge_11),
          lm(moved_for_job_total ~ yppals, data = full_data_merge_11),
          omit.stat = c("adj.rsq","ser", "f"),
          omit.table.layout = c("n"),
          type = 'text')

stargazer(lm(moved_for_education_total ~ ypnpal, data = full_data_merge_11),
          lm(moved_for_education_total ~ ypfpark, data = full_data_merge_11),
          lm(moved_for_education_total ~ ypmkfrn, data = full_data_merge_11),
          lm(moved_for_education_total ~ yppalo, data = full_data_merge_11),
          lm(moved_for_education_total ~ yppals, data = full_data_merge_11),
          omit.stat = c("adj.rsq","ser", "f"),
          omit.table.layout = c("n"),
          type = 'text')




stargazer(lm(moved_total ~ ypnpal, data = full_data_merge_13),
          lm(moved_total ~ ypfpark, data = full_data_merge_13),
          lm(moved_total ~ ypmkfrn, data = full_data_merge_13),
          lm(moved_total ~ yppalo, data = full_data_merge_13),
          lm(moved_total ~ yppals, data = full_data_merge_13),
          omit.stat = c("adj.rsq","ser", "f"),
          omit.table.layout = c("n"),
          type = 'text')

stargazer(lm(moved_for_job_total ~ ypnpal, data = full_data_merge_13),
          lm(moved_for_job_total ~ ypfpark, data = full_data_merge_13),
          lm(moved_for_job_total ~ ypmkfrn, data = full_data_merge_13),
          lm(moved_for_job_total ~ yppalo, data = full_data_merge_13),
          lm(moved_for_job_total ~ yppals, data = full_data_merge_13),
          omit.stat = c("adj.rsq","ser", "f"),
          omit.table.layout = c("n"),
          type = 'text')

stargazer(lm(moved_for_education_total ~ ypnpal, data = full_data_merge_13),
          lm(moved_for_education_total ~ ypfpark, data = full_data_merge_13),
          lm(moved_for_education_total ~ ypmkfrn, data = full_data_merge_13),
          lm(moved_for_education_total ~ yppalo, data = full_data_merge_13),
          lm(moved_for_education_total ~ yppals, data = full_data_merge_13),
          omit.stat = c("adj.rsq","ser", "f"),
          omit.table.layout = c("n"),
          type = 'text')



stargazer(lm(moved_total ~ ypnpal, data = full_data_merge_15),
          lm(moved_total ~ ypfpark, data = full_data_merge_15),
          lm(moved_total ~ ypmkfrn, data = full_data_merge_15),
          lm(moved_total ~ yppalo, data = full_data_merge_15),
          lm(moved_total ~ yppals, data = full_data_merge_15),
          omit.stat = c("adj.rsq","ser", "f"),
          omit.table.layout = c("n"),
          type = 'text')

stargazer(lm(moved_for_job_total ~ ypnpal, data = full_data_merge_15),
          lm(moved_for_job_total ~ ypfpark, data = full_data_merge_15),
          lm(moved_for_job_total ~ ypmkfrn, data = full_data_merge_15),
          lm(moved_for_job_total ~ yppalo, data = full_data_merge_15),
          lm(moved_for_job_total ~ yppals, data = full_data_merge_15),
          omit.stat = c("adj.rsq","ser", "f"),
          omit.table.layout = c("n"),
          type = 'text')

stargazer(lm(moved_for_education_total ~ ypnpal, data = full_data_merge_15),
          lm(moved_for_education_total ~ ypfpark, data = full_data_merge_15),
          lm(moved_for_education_total ~ ypmkfrn, data = full_data_merge_15),
          lm(moved_for_education_total ~ yppalo, data = full_data_merge_15),
          lm(moved_for_education_total ~ yppals, data = full_data_merge_15),
          omit.stat = c("adj.rsq","ser", "f"),
          omit.table.layout = c("n"),
          type = 'text')
```
