---
title: "moving_regressions"
author: "Adam Drożyński"
date: "4/15/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
library(pacman)
p_load(tictoc,tidyverse,dplyr,broom,ggplot2,clubSandwich,
       data.table,matrixStats,magrittr,MASS,R.utils,
       stargazer,DT,furrr, lfe,estimatr,boot,plm,lmtest,multiwayvcov,
       sandwich,glmnet,ISLR, parallel, haven, MatchIt, optmatch, ipw, AER, rdd)

data_adults_merged = read.csv('data_adults_merged.csv')
```

Moving - regressions
```{r}
lm1 <- felm(income ~ moved_times | year + pidp + age | 0 | pidp, 
       data = data_adults_merged)
lm2 <- felm(income ~ moved_for_job_times | year + pidp + age | 0 | pidp, 
       data = data_adults_merged)
lm3 <- felm(income ~ moved_for_family_times | year + pidp + age | 0 | pidp, 
       data = data_adults_merged)
lm4 <- felm(income ~ moved_for_education_times | year + pidp + age | 0 | pidp, 
       data = data_adults_merged)
lm5 <- felm(income ~ moved_for_housing_times | year + pidp + age | 0 | pidp, 
       data = data_adults_merged)
lm6 <- felm(income ~ moved_for_area_times | year + pidp + age | 0 | pidp, 
       data = data_adults_merged)
lm7 <- felm(income ~ moved_for_career_times | year + pidp + age | 0 | pidp, 
       data = data_adults_merged)

lm8 <- 
  felm(income ~ moved_times + moved_for_job_times + 
                moved_for_family_times + moved_for_education_times +
                moved_for_housing_times + moved_for_area_times 
                  | year + pidp + age | 0 | pidp, 
       data = data_adults_merged)

stargazer(lm1, lm2, lm3, lm4, lm5, omit.stat = c("adj.rsq","ser", "f"),
          omit.table.layout = c("n"), type = 'text')
stargazer(lm6, lm7, lm8, omit.stat = c("adj.rsq","ser", "f"),
          omit.table.layout = c("n"), type = 'text')
```

